// Code generated by ent, DO NOT EDIT.

package ent

import (
	"showcase/ent/schema"
	"showcase/ent/session"
	"showcase/ent/user"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescTokenHash is the schema descriptor for token_hash field.
	sessionDescTokenHash := sessionFields[1].Descriptor()
	// session.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	session.TokenHashValidator = sessionDescTokenHash.Validators[0].(func(string) error)
	// sessionDescID is the schema descriptor for id field.
	sessionDescID := sessionFields[0].Descriptor()
	// session.DefaultID holds the default value on creation for the id field.
	session.DefaultID = sessionDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescProfileLink is the schema descriptor for profile_link field.
	userDescProfileLink := userFields[1].Descriptor()
	// user.DefaultProfileLink holds the default value on creation for the profile_link field.
	user.DefaultProfileLink = userDescProfileLink.Default.(string)
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[2].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[4].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
