// Code generated by ent, DO NOT EDIT.

package ent

import (
	"showcase/ent/schema"
	"showcase/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(int) error)
	// userDescProfileLink is the schema descriptor for profile_link field.
	userDescProfileLink := userFields[1].Descriptor()
	// user.DefaultProfileLink holds the default value on creation for the profile_link field.
	user.DefaultProfileLink = userDescProfileLink.Default.(string)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[3].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
}
