name: Pushing backend to quay

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: login to quay
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: build docker image
        if: github.event_name == 'push'
        run: |
          docker build --file Dockerfile --tag quay.io/showcase/showcase:${GITHUB_SHA} .

      - name: push docker image
        if: github.event_name == 'push'
        run: docker push quay.io/showcase/showcase:${GITHUB_SHA}
       
      - name: checkout gitops repo
        if: github.event_name == 'push'
        uses: actions/checkout@v4
        with:
          repository: CANUreal/showcase-gitops
          token: ${{ secrets.GITOPS_TOKEN }}
          path: gitops

      - name: update deployment image number
        if: github.event_name == 'push'
        run: |
          sed -i "s#image: quay.io/showcase/showcase:.*#image: quay.io/showcase/showcase:${GITHUB_SHA}#g" gitops/apps/showcase-backend/deployment.yaml
      - name: create temp secret from .env
        if: github.event_name == 'push'
        run: |
          kubectl create secret generic showcase-backend-secrets \
            --from-env-file=backend/.env \
            --dry-run=client -o yaml > temp-secret.yaml

      - name: install kubeseal    
        if: github.event_name == 'push'
        run: |
          curl -L https://github.com/bitnami-labs/sealed-secrets/releases/latest/download/kubeseal-linux-amd64 -o kubeseal
          chmod +x kubeseal
          sudo mv kubeseal /usr/local/bin/
          
      - name: seal the secret 
        if: github.event_name == 'push'
        run: |
          # DİKKAT: Çıktıyı DOĞRUDAN gitops klasörünün içine yaz!
          kubeseal --namespace showcase -o yaml < temp-secret.yaml > gitops/apps/showcase-backend/sealed-secret.yaml

      - name: commit and push gitops change
        if: github.event_name == 'push'
        run: |
          cd gitops

          git config user.name "actions[bot]"
          git config user.email "12332343+actions[bot]@users.noreply.github.com"

          # HEM deployment.yaml HEM sealed-secret.yaml EKLE
          git add apps/showcase-backend/deployment.yaml
          git add apps/showcase-backend/sealed-secret.yaml
          
          git commit -m "updated showcase-backend image to ${GITHUB_SHA} and sealed secret" || exit 0
          git push 
